// <auto-generated />
using System;
using Blogic_task.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blogic_task.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blogic_task.Models.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodneCislo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klienti");
                });

            modelBuilder.Entity("Blogic_task.Models.Poradce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodneCislo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Poradci");
                });

            modelBuilder.Entity("Blogic_task.Models.Smlouva", b =>
                {
                    b.Property<string>("EvidencniCislo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DatumPlatnosti")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumUkonceni")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumUzavreni")
                        .HasColumnType("datetime2");

                    b.Property<int>("Instituce")
                        .HasColumnType("int");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("SpravceId")
                        .HasColumnType("int");

                    b.HasKey("EvidencniCislo");

                    b.HasIndex("KlientId");

                    b.HasIndex("SpravceId");

                    b.ToTable("Smlouvy");
                });

            modelBuilder.Entity("PoradceSmlouva", b =>
                {
                    b.Property<int>("DalsiPoradciId")
                        .HasColumnType("int");

                    b.Property<string>("DalsiSmlouvyEvidencniCislo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DalsiPoradciId", "DalsiSmlouvyEvidencniCislo");

                    b.HasIndex("DalsiSmlouvyEvidencniCislo");

                    b.ToTable("SmlouvaDalsiPoradce", (string)null);
                });

            modelBuilder.Entity("Blogic_task.Models.Smlouva", b =>
                {
                    b.HasOne("Blogic_task.Models.Klient", "Klient")
                        .WithMany("Smlouvy")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blogic_task.Models.Poradce", "Spravce")
                        .WithMany("SpravovaneSmlouvy")
                        .HasForeignKey("SpravceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Spravce");
                });

            modelBuilder.Entity("PoradceSmlouva", b =>
                {
                    b.HasOne("Blogic_task.Models.Poradce", null)
                        .WithMany()
                        .HasForeignKey("DalsiPoradciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blogic_task.Models.Smlouva", null)
                        .WithMany()
                        .HasForeignKey("DalsiSmlouvyEvidencniCislo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blogic_task.Models.Klient", b =>
                {
                    b.Navigation("Smlouvy");
                });

            modelBuilder.Entity("Blogic_task.Models.Poradce", b =>
                {
                    b.Navigation("SpravovaneSmlouvy");
                });
#pragma warning restore 612, 618
        }
    }
}
